[workspace]
members = [".", "testing/bsc-ef-tests"]

[package]
name = "reth_bsc"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "reth_bsc"
path = "src/lib.rs"

[[bin]]
name = "reth-bsc"
path = "src/main.rs"

[dependencies]
reth = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-cli = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-cli-commands = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-basic-payload-builder = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-db = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-engine-local = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-engine-tree = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-node-builder = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-chainspec = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-cli-util = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-discv4 = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59", features = [
    "test-utils",
] }
reth-engine-primitives = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-ethereum-forks = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59", features = [
    "serde",
] }
reth-ethereum-payload-builder = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-payload-builder-primitives = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-chain-state = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-ethereum-primitives = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-eth-wire = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-eth-wire-types = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-evm = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-evm-ethereum = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-execution-types = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-ipc = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-metrics = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-node-core = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-revm = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-network = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59", features = [
    "test-utils",
] }
reth-network-p2p = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-network-api = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-node-ethereum = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59", features = [
    "test-utils",
] }
reth-network-peers = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-payload-primitives = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-ethereum-engine-primitives = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-primitives-traits = { version = "0.5.0", default-features = false }
reth-codecs = { version = "0.5.0" }
reth-provider = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59", features = [
    "test-utils",
] }
reth-rpc-eth-api = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-rpc-convert = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-rpc-engine-api = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-rpc-server-types = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-trie-common = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-trie-db = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-tasks = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }
reth-transaction-pool = { git = "https://github.com/bnb-chain/reth.git", rev = "0dea17d20f358768ac2d458bef170d8f0ab1df59" }

revm = "38.0.0"
revm-database = "13.0.0"
revm-bytecode = "10.0.0"
revm-state = "11.0.0"
revm-primitives = { version = "23.0.0", default-features = false }
revm-interpreter = "35.0.0"
revm-database-interface = "11.0.0"

# alloy dependencies
alloy-evm = { version = "0.34.0", features = ["rpc"] }

alloy-genesis = "2.0.4"
alloy-consensus = "2.0.4"
alloy-eips = "2.0.4"
alloy-network = "2.0.4"
alloy-rpc-types = { version = "2.0.4", features = ["eth"] }
alloy-rpc-types-eth = "2.0.4"
alloy-rpc-types-engine = "2.0.4"
alloy-rpc-types-mev = "2.0.4"
alloy-signer = "2.0.4"

alloy-chains = "0.2.33"
alloy-rlp = { version = "0.3.13", default-features = false, features = [
    "core-net",
] }

alloy-dyn-abi = "1.5.6"
alloy-json-abi = { version = "1.5.6", default-features = false }
alloy-primitives = { version = "1.5.6", default-features = false, features = [
    "map-foldhash",
] }
alloy-sol-macro = "1.5.6"
alloy-sol-types = { version = "1.5.6", default-features = false }

jsonrpsee = { version = "0.26.0", features = ["server", "client", "macros"] }
jsonrpsee-core = { version = "0.26.0", features = ["server"] }
jsonrpsee-types = "0.26.0"

# misc dependencies
auto_impl = "1"
async-trait = "0.1"
bytes = "1.5"
clap = { version = "4.4", features = ["derive"] }
cfg-if = { version = "1.0", default-features = false }
derive_more = "0.99"
eyre = "0.6"
futures = "0.3"
either = "1"
hex = "0.4"
lazy_static = "1.4.0"
lru = "0.12"
metrics = "0.24"
phf = { version = "0.11", features = ["macros"] }
once_cell = { version = "1.19", default-features = false, features = ["alloc"] }
parity-bytes = { version = "0.1.2", default-features = false }
parking_lot = "0.12"
secp256k1 = { version = "0.30", features = [
    "global-context",
    "std",
    "recovery",
] }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
serde_cbor = "0.11"
schnellru = "0.2"
thiserror = "2.0"
tokio = { version = "1.44", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
bit-set = "0.5.3"
rand = "0.9"
zeroize = "1"
# For EIP-2335 BLS keystore support
aes = "0.8"
ctr = "0.9"
cipher = "0.4"
sha2 = "0.10"
pbkdf2 = "0.12"
scrypt = "0.11"

# precompiles deps
bls_on_arkworks = "0.3.0"
blst = "0.3.15"

cometbft = { git = "https://github.com/bnb-chain/greenfield-cometbft-rs.git", rev = "1282547" }
cometbft-light-client-verifier = { git = "https://github.com/bnb-chain/greenfield-cometbft-rs.git", rev = "1282547" }
cometbft-proto = { git = "https://github.com/bnb-chain/greenfield-cometbft-rs.git", rev = "1282547" }
cometbft-light-client = { git = "https://github.com/bnb-chain/greenfield-cometbft-rs.git", rev = "1282547" }

prost = { version = "0.12.6" }

tendermint = { git = "https://github.com/bnb-chain/tendermint-rs-parlia", rev = "8c21ccbd58a174e07eed2c9343e63ccd00f0fbd5", features = [
    "secp256k1",
] }
signature = "2.2.0"
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }
eth-keystore = "0.5"

[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = "0.6"
tikv-jemallocator = { version = "0.6", optional = true }
libc = "0.2"

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator", "reth/jemalloc"]
dev = ["reth-cli-commands/arbitrary", "reth/dev", "revm/dev"]
asm-keccak = [
    "reth/asm-keccak",
    "reth-node-core/asm-keccak",
    "reth-node-ethereum/asm-keccak",
]

serde = [
    "alloy-chains/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "alloy-rpc-types-engine/serde",
    "alloy-rpc-types-eth/serde",
    "bytes/serde",
    "parking_lot/serde",
    "reth-eth-wire/serde",
    "reth-eth-wire-types/serde",
    "reth-ethereum-forks/serde",
    "reth-ethereum-primitives/serde",
    "reth-network/serde",
    "reth-network-api/serde",
    "reth-primitives-traits/serde",
    "reth-revm/serde",
    "reth-trie-common/serde",
    "reth-trie-db/serde",
    "revm/serde",
    "secp256k1/serde",
]

client = [
    "jsonrpsee/client",
    "jsonrpsee/async-client",
    "reth-rpc-eth-api/client",
]

bench-test = []

# Use the `--profile profiling` flag to show symbols in release mode.
# e.g. `cargo build --profile profiling`
[profile.profiling]
inherits = "release"
debug = "full"
strip = "none"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
# Keep line-tables so flamegraph frames carry Rust function names. Without this
# the maxperf binary is stripped (inherited from [profile.release]) and every
# reth-bsc frame collapses to a single `[reth-bsc]` bar in the SVG.
debug = "line-tables-only"
strip = false
split-debuginfo = "off"

# Apply the same to every transitive dependency so revm/rayon frames also
# resolve. Without this, only reth-bsc's own symbols show up and the whole
# state-root path still looks opaque.
[profile.maxperf.package."*"]
debug = "line-tables-only"
strip = false

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }

[patch."https://github.com/bnb-chain/reth.git"]
custom-hardforks = { path = "/Users/chee/Documents/repo/reth/examples/custom-hardforks" }
ef-test-runner = { path = "/Users/chee/Documents/repo/reth/testing/runner" }
ef-tests = { path = "/Users/chee/Documents/repo/reth/testing/ef-tests" }
example-beacon-api-sidecar-fetcher = { path = "/Users/chee/Documents/repo/reth/examples/beacon-api-sidecar-fetcher" }
example-beacon-api-sse = { path = "/Users/chee/Documents/repo/reth/examples/beacon-api-sse" }
example-bsc-p2p = { path = "/Users/chee/Documents/repo/reth/examples/bsc-p2p" }
example-custom-auth-http-middleware = { path = "/Users/chee/Documents/repo/reth/examples/custom-auth-http-middleware" }
example-custom-beacon-withdrawals = { path = "/Users/chee/Documents/repo/reth/examples/custom-beacon-withdrawals" }
example-custom-dev-node = { path = "/Users/chee/Documents/repo/reth/examples/custom-dev-node" }
example-custom-engine-types = { path = "/Users/chee/Documents/repo/reth/examples/custom-engine-types" }
example-custom-evm = { path = "/Users/chee/Documents/repo/reth/examples/custom-evm" }
example-custom-inspector = { path = "/Users/chee/Documents/repo/reth/examples/custom-inspector" }
example-custom-node-components = { path = "/Users/chee/Documents/repo/reth/examples/custom-node-components" }
example-custom-payload-builder = { path = "/Users/chee/Documents/repo/reth/examples/custom-payload-builder" }
example-custom-rlpx-subprotocol = { path = "/Users/chee/Documents/repo/reth/examples/custom-rlpx-subprotocol" }
example-custom-rpc-middleware = { path = "/Users/chee/Documents/repo/reth/examples/custom-rpc-middleware" }
example-custom-state-root = { path = "/Users/chee/Documents/repo/reth/examples/custom-state-root" }
example-db-access = { path = "/Users/chee/Documents/repo/reth/examples/db-access" }
example-exex-test = { path = "/Users/chee/Documents/repo/reth/examples/exex-test" }
example-full-contract-state = { path = "/Users/chee/Documents/repo/reth/examples/full-contract-state" }
example-manual-p2p = { path = "/Users/chee/Documents/repo/reth/examples/manual-p2p" }
example-network = { path = "/Users/chee/Documents/repo/reth/examples/network" }
example-network-proxy = { path = "/Users/chee/Documents/repo/reth/examples/network-proxy" }
example-network-txpool = { path = "/Users/chee/Documents/repo/reth/examples/network-txpool" }
example-node-builder-api = { path = "/Users/chee/Documents/repo/reth/examples/node-builder-api" }
example-node-custom-rpc = { path = "/Users/chee/Documents/repo/reth/examples/node-custom-rpc" }
example-node-event-hooks = { path = "/Users/chee/Documents/repo/reth/examples/node-event-hooks" }
example-polygon-p2p = { path = "/Users/chee/Documents/repo/reth/examples/polygon-p2p" }
example-precompile-cache = { path = "/Users/chee/Documents/repo/reth/examples/precompile-cache" }
example-rpc-db = { path = "/Users/chee/Documents/repo/reth/examples/rpc-db" }
example-txpool-tracing = { path = "/Users/chee/Documents/repo/reth/examples/txpool-tracing" }
exex-subscription = { path = "/Users/chee/Documents/repo/reth/examples/exex-subscription" }
reth = { path = "/Users/chee/Documents/repo/reth/bin/reth" }
reth-basic-payload-builder = { path = "/Users/chee/Documents/repo/reth/crates/payload/basic" }
reth-bb = { path = "/Users/chee/Documents/repo/reth/bin/reth-bb" }
reth-chain-state = { path = "/Users/chee/Documents/repo/reth/crates/chain-state" }
reth-chainspec = { path = "/Users/chee/Documents/repo/reth/crates/chainspec" }
reth-cli = { path = "/Users/chee/Documents/repo/reth/crates/cli/cli" }
reth-cli-commands = { path = "/Users/chee/Documents/repo/reth/crates/cli/commands" }
reth-cli-runner = { path = "/Users/chee/Documents/repo/reth/crates/cli/runner" }
reth-cli-util = { path = "/Users/chee/Documents/repo/reth/crates/cli/util" }
reth-config = { path = "/Users/chee/Documents/repo/reth/crates/config" }
reth-consensus = { path = "/Users/chee/Documents/repo/reth/crates/consensus/consensus" }
reth-consensus-common = { path = "/Users/chee/Documents/repo/reth/crates/consensus/common" }
reth-consensus-debug-client = { path = "/Users/chee/Documents/repo/reth/crates/consensus/debug-client" }
reth-db = { path = "/Users/chee/Documents/repo/reth/crates/storage/db" }
reth-db-api = { path = "/Users/chee/Documents/repo/reth/crates/storage/db-api" }
reth-db-common = { path = "/Users/chee/Documents/repo/reth/crates/storage/db-common" }
reth-db-models = { path = "/Users/chee/Documents/repo/reth/crates/storage/db-models" }
reth-discv4 = { path = "/Users/chee/Documents/repo/reth/crates/net/discv4" }
reth-discv5 = { path = "/Users/chee/Documents/repo/reth/crates/net/discv5" }
reth-dns-discovery = { path = "/Users/chee/Documents/repo/reth/crates/net/dns" }
reth-downloaders = { path = "/Users/chee/Documents/repo/reth/crates/net/downloaders" }
reth-e2e-test-utils = { path = "/Users/chee/Documents/repo/reth/crates/e2e-test-utils" }
reth-ecies = { path = "/Users/chee/Documents/repo/reth/crates/net/ecies" }
reth-engine-local = { path = "/Users/chee/Documents/repo/reth/crates/engine/local" }
reth-engine-primitives = { path = "/Users/chee/Documents/repo/reth/crates/engine/primitives" }
reth-engine-tree = { path = "/Users/chee/Documents/repo/reth/crates/engine/tree" }
reth-engine-util = { path = "/Users/chee/Documents/repo/reth/crates/engine/util" }
reth-era = { path = "/Users/chee/Documents/repo/reth/crates/era" }
reth-era-downloader = { path = "/Users/chee/Documents/repo/reth/crates/era-downloader" }
reth-era-utils = { path = "/Users/chee/Documents/repo/reth/crates/era-utils" }
reth-errors = { path = "/Users/chee/Documents/repo/reth/crates/errors" }
reth-eth-wire = { path = "/Users/chee/Documents/repo/reth/crates/net/eth-wire" }
reth-eth-wire-types = { path = "/Users/chee/Documents/repo/reth/crates/net/eth-wire-types" }
reth-ethereum = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/reth" }
reth-ethereum-cli = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/cli" }
reth-ethereum-consensus = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/consensus" }
reth-ethereum-engine-primitives = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/engine-primitives" }
reth-ethereum-forks = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/hardforks" }
reth-ethereum-payload-builder = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/payload" }
reth-ethereum-primitives = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/primitives" }
reth-etl = { path = "/Users/chee/Documents/repo/reth/crates/etl" }
reth-evm = { path = "/Users/chee/Documents/repo/reth/crates/evm/evm" }
reth-evm-ethereum = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/evm" }
reth-execution-cache = { path = "/Users/chee/Documents/repo/reth/crates/engine/execution-cache" }
reth-execution-errors = { path = "/Users/chee/Documents/repo/reth/crates/evm/execution-errors" }
reth-execution-types = { path = "/Users/chee/Documents/repo/reth/crates/evm/execution-types" }
reth-exex = { path = "/Users/chee/Documents/repo/reth/crates/exex/exex" }
reth-exex-test-utils = { path = "/Users/chee/Documents/repo/reth/crates/exex/test-utils" }
reth-exex-types = { path = "/Users/chee/Documents/repo/reth/crates/exex/types" }
reth-fs-util = { path = "/Users/chee/Documents/repo/reth/crates/fs-util" }
reth-invalid-block-hooks = { path = "/Users/chee/Documents/repo/reth/crates/engine/invalid-block-hooks" }
reth-ipc = { path = "/Users/chee/Documents/repo/reth/crates/rpc/ipc" }
reth-libmdbx = { path = "/Users/chee/Documents/repo/reth/crates/storage/libmdbx-rs" }
reth-mdbx-sys = { path = "/Users/chee/Documents/repo/reth/crates/storage/libmdbx-rs/mdbx-sys" }
reth-metrics = { path = "/Users/chee/Documents/repo/reth/crates/metrics" }
reth-net-banlist = { path = "/Users/chee/Documents/repo/reth/crates/net/banlist" }
reth-net-nat = { path = "/Users/chee/Documents/repo/reth/crates/net/nat" }
reth-network = { path = "/Users/chee/Documents/repo/reth/crates/net/network" }
reth-network-api = { path = "/Users/chee/Documents/repo/reth/crates/net/network-api" }
reth-network-p2p = { path = "/Users/chee/Documents/repo/reth/crates/net/p2p" }
reth-network-peers = { path = "/Users/chee/Documents/repo/reth/crates/net/peers" }
reth-network-types = { path = "/Users/chee/Documents/repo/reth/crates/net/network-types" }
reth-nippy-jar = { path = "/Users/chee/Documents/repo/reth/crates/storage/nippy-jar" }
reth-node-api = { path = "/Users/chee/Documents/repo/reth/crates/node/api" }
reth-node-builder = { path = "/Users/chee/Documents/repo/reth/crates/node/builder" }
reth-node-core = { path = "/Users/chee/Documents/repo/reth/crates/node/core" }
reth-node-ethereum = { path = "/Users/chee/Documents/repo/reth/crates/ethereum/node" }
reth-node-ethstats = { path = "/Users/chee/Documents/repo/reth/crates/node/ethstats" }
reth-node-events = { path = "/Users/chee/Documents/repo/reth/crates/node/events" }
reth-node-metrics = { path = "/Users/chee/Documents/repo/reth/crates/node/metrics" }
reth-node-types = { path = "/Users/chee/Documents/repo/reth/crates/node/types" }
reth-payload-builder = { path = "/Users/chee/Documents/repo/reth/crates/payload/builder" }
reth-payload-builder-primitives = { path = "/Users/chee/Documents/repo/reth/crates/payload/builder-primitives" }
reth-payload-primitives = { path = "/Users/chee/Documents/repo/reth/crates/payload/primitives" }
reth-payload-util = { path = "/Users/chee/Documents/repo/reth/crates/payload/util" }
reth-payload-validator = { path = "/Users/chee/Documents/repo/reth/crates/payload/validator" }
reth-provider = { path = "/Users/chee/Documents/repo/reth/crates/storage/provider" }
reth-prune = { path = "/Users/chee/Documents/repo/reth/crates/prune/prune" }
reth-prune-db = { path = "/Users/chee/Documents/repo/reth/crates/prune/db" }
reth-prune-types = { path = "/Users/chee/Documents/repo/reth/crates/prune/types" }
reth-revm = { path = "/Users/chee/Documents/repo/reth/crates/revm" }
reth-rpc = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc" }
reth-rpc-api = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-api" }
reth-rpc-api-testing-util = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-testing-util" }
reth-rpc-builder = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-builder" }
reth-rpc-convert = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-convert" }
reth-rpc-e2e-tests = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-e2e-tests" }
reth-rpc-engine-api = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-engine-api" }
reth-rpc-eth-api = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-eth-api" }
reth-rpc-eth-types = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-eth-types" }
reth-rpc-layer = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-layer" }
reth-rpc-server-types = { path = "/Users/chee/Documents/repo/reth/crates/rpc/rpc-server-types" }
reth-stages = { path = "/Users/chee/Documents/repo/reth/crates/stages/stages" }
reth-stages-api = { path = "/Users/chee/Documents/repo/reth/crates/stages/api" }
reth-stages-types = { path = "/Users/chee/Documents/repo/reth/crates/stages/types" }
reth-static-file = { path = "/Users/chee/Documents/repo/reth/crates/static-file/static-file" }
reth-static-file-types = { path = "/Users/chee/Documents/repo/reth/crates/static-file/types" }
reth-storage-api = { path = "/Users/chee/Documents/repo/reth/crates/storage/storage-api" }
reth-storage-errors = { path = "/Users/chee/Documents/repo/reth/crates/storage/errors" }
reth-storage-rpc-provider = { path = "/Users/chee/Documents/repo/reth/crates/storage/rpc-provider" }
reth-tasks = { path = "/Users/chee/Documents/repo/reth/crates/tasks" }
reth-testing-utils = { path = "/Users/chee/Documents/repo/reth/testing/testing-utils" }
reth-tokio-util = { path = "/Users/chee/Documents/repo/reth/crates/tokio-util" }
reth-tracing = { path = "/Users/chee/Documents/repo/reth/crates/tracing" }
reth-tracing-otlp = { path = "/Users/chee/Documents/repo/reth/crates/tracing-otlp" }
reth-transaction-pool = { path = "/Users/chee/Documents/repo/reth/crates/transaction-pool" }
reth-trie = { path = "/Users/chee/Documents/repo/reth/crates/trie/trie" }
reth-trie-common = { path = "/Users/chee/Documents/repo/reth/crates/trie/common" }
reth-trie-db = { path = "/Users/chee/Documents/repo/reth/crates/trie/db" }
reth-trie-parallel = { path = "/Users/chee/Documents/repo/reth/crates/trie/parallel" }
reth-trie-sparse = { path = "/Users/chee/Documents/repo/reth/crates/trie/sparse" }
